steps: 
  - name: europe-west1-docker.pkg.dev/tech-rnd-project/mymailer:latest
    args: 
      - /bin/sh
      - "-c"
      - |
          echo $$MSMTP_PASSWORD > /dev/null
          echo "body" | mutt -s "subj" -a att.file -- divyashet543@gmail.com
    availableSecrets: ~
    env: MSMTP_PASSWORD
    name: "europe-west1-docker.pkg.dev/[...]/mymailer:latest"
    secretEnv: 
      - MSMTP_PASSWORD
    secretManager: 
      - 
        versionName: projects/460440866465/secrets/msmtp_password/versions/1
